<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Parishes;


class ParishesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Parishes::create(['name' => 'Alto Orinoco', 'id_municipalities' => '1']);
        Parishes::create(['name' => 'Alto Orinoco', 'id_municipalities' => '1']);
        Parishes::create(['name' => 'Huachamacare Acanaña', 'id_municipalities' => '1']);
        Parishes::create(['name' => 'Marawaka Toky Shamanaña', 'id_municipalities' => '1']);
        Parishes::create(['name' => 'Mavaka Mavaka', 'id_municipalities' => '1']);
        Parishes::create(['name' => 'Sierra Parima Parimabé', 'id_municipalities' => '1']);
        Parishes::create(['name' => 'Ucata Laja Lisa', 'id_municipalities' => '2']);
        Parishes::create(['name' => 'Yapacana Macuruco', 'id_municipalities' => '2']);
        Parishes::create(['name' => 'Caname Guarinuma', 'id_municipalities' => '2']);
        Parishes::create(['name' => 'Fernando Girón Tovar', 'id_municipalities' => '3']);
        Parishes::create(['name' => 'Luis Alberto Gómez', 'id_municipalities' => '3']);
        Parishes::create(['name' => 'Pahueña Limón de Parhueña', 'id_municipalities' => '3']);
        Parishes::create(['name' => 'Platanillal Platanillal', 'id_municipalities' => '3']);
        Parishes::create(['name' => 'Samariapo', 'id_municipalities' => '4']);
        Parishes::create(['name' => 'Sipapo', 'id_municipalities' => '4']);
        Parishes::create(['name' => 'Munduapo', 'id_municipalities' => '4']);
        Parishes::create(['name' => 'Guayapo', 'id_municipalities' => '4']);
        Parishes::create(['name' => 'Alto Ventuari', 'id_municipalities' => '5']);
        Parishes::create(['name' => 'Medio Ventuari', 'id_municipalities' => '5']);
        Parishes::create(['name' => 'Bajo Ventuari', 'id_municipalities' => '5']);
        Parishes::create(['name' => 'Victorino', 'id_municipalities' => '6']);
        Parishes::create(['name' => 'Comunidad', 'id_municipalities' => '6']);
        Parishes::create(['name' => 'Casiquiare', 'id_municipalities' => '7']);
        Parishes::create(['name' => 'Cocuy', 'id_municipalities' => '7']);
        Parishes::create(['name' => 'San Carlos de Río Negro', 'id_municipalities' => '7']);
        Parishes::create(['name' => 'Solano', 'id_municipalities' => '7']);
        Parishes::create(['name' => 'Anaco', 'id_municipalities' => '8']);
        Parishes::create(['name' => 'San Joaquín', 'id_municipalities' => '8']);
        Parishes::create(['name' => 'Cachipo', 'id_municipalities' => '9']);
        Parishes::create(['name' => 'Aragua de Barcelona', 'id_municipalities' => '9']);
        Parishes::create(['name' => 'Lechería', 'id_municipalities' => '11']);
        Parishes::create(['name' => 'El Morro', 'id_municipalities' => '11']);
        Parishes::create(['name' => 'Puerto Píritu', 'id_municipalities' => '12']);
        Parishes::create(['name' => 'San Miguel', 'id_municipalities' => '12']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '12']);
        Parishes::create(['name' => 'Valle de Guanape', 'id_municipalities' => '13']);
        Parishes::create(['name' => 'Santa Bárbara', 'id_municipalities' => '13']);
        Parishes::create(['name' => 'El Chaparro', 'id_municipalities' => '14']);
        Parishes::create(['name' => 'Tomás Alfaro', 'id_municipalities' => '14']);
        Parishes::create(['name' => 'Calatrava', 'id_municipalities' => '14']);
        Parishes::create(['name' => 'Guanta', 'id_municipalities' => '15']);
        Parishes::create(['name' => 'Chorrerón', 'id_municipalities' => '15']);
        Parishes::create(['name' => 'Mamo', 'id_municipalities' => '16']);
        Parishes::create(['name' => 'Soledad', 'id_municipalities' => '16']);
        Parishes::create(['name' => 'Mapire', 'id_municipalities' => '17']);
        Parishes::create(['name' => 'Piar', 'id_municipalities' => '17']);
        Parishes::create(['name' => 'Santa Clara', 'id_municipalities' => '17']);
        Parishes::create(['name' => 'San Diego de Cabrutica', 'id_municipalities' => '17']);
        Parishes::create(['name' => 'Uverito', 'id_municipalities' => '17']);
        Parishes::create(['name' => 'Zuata', 'id_municipalities' => '17']);
        Parishes::create(['name' => 'Puerto La Cruz', 'id_municipalities' => '18']);
        Parishes::create(['name' => 'Pozuelos', 'id_municipalities' => '18']);
        Parishes::create(['name' => 'Onoto', 'id_municipalities' => '19']);
        Parishes::create(['name' => 'San Pablo', 'id_municipalities' => '19']);
        Parishes::create(['name' => 'San Mateo', 'id_municipalities' => '20']);
        Parishes::create(['name' => 'El Carito', 'id_municipalities' => '20']);
        Parishes::create(['name' => 'Santa Inés', 'id_municipalities' => '20']);
        Parishes::create(['name' => 'La Romereña', 'id_municipalities' => '20']);
        Parishes::create(['name' => 'Atapirire', 'id_municipalities' => '21']);
        Parishes::create(['name' => 'Boca del Pao', 'id_municipalities' => '21']);
        Parishes::create(['name' => 'El Pao', 'id_municipalities' => '21']);
        Parishes::create(['name' => 'Pariaguán', 'id_municipalities' => '21']);
        Parishes::create(['name' => 'Cantaura', 'id_municipalities' => '22']);
        Parishes::create(['name' => 'Libertador', 'id_municipalities' => '22']);
        Parishes::create(['name' => 'Santa Rosa', 'id_municipalities' => '22']);
        Parishes::create(['name' => 'Urica', 'id_municipalities' => '22']);
        Parishes::create(['name' => 'Píritu', 'id_municipalities' => '23']);
        Parishes::create(['name' => 'San Francisco', 'id_municipalities' => '23']);
        Parishes::create(['name' => 'San José de Guanipa', 'id_municipalities' => '24']);
        Parishes::create(['name' => 'Boca de Uchire', 'id_municipalities' => '25']);
        Parishes::create(['name' => 'Boca de Chávez', 'id_municipalities' => '25']);
        Parishes::create(['name' => 'Pueblo Nuevo', 'id_municipalities' => '26']);
        Parishes::create(['name' => 'Santa Ana', 'id_municipalities' => '26']);
        Parishes::create(['name' => 'Bergantín', 'id_municipalities' => '27']);
        Parishes::create(['name' => 'Caigua', 'id_municipalities' => '27']);
        Parishes::create(['name' => 'El Carmen', 'id_municipalities' => '27']);
        Parishes::create(['name' => 'El Pilar', 'id_municipalities' => '27']);
        Parishes::create(['name' => 'Naricual', 'id_municipalities' => '27']);
        Parishes::create(['name' => 'San Crsitóbal', 'id_municipalities' => '27']);
        Parishes::create(['name' => 'Edmundo Barrios', 'id_municipalities' => '28']);
        Parishes::create(['name' => 'Miguel Otero Silva', 'id_municipalities' => '28']);
        Parishes::create(['name' => 'Achaguas', 'id_municipalities' => '29']);
        Parishes::create(['name' => 'Apurito', 'id_municipalities' => '29']);
        Parishes::create(['name' => 'El Yagual', 'id_municipalities' => '29']);
        Parishes::create(['name' => 'Guachara', 'id_municipalities' => '29']);
        Parishes::create(['name' => 'Mucuritas', 'id_municipalities' => '29']);
        Parishes::create(['name' => 'Queseras del medio', 'id_municipalities' => '29']);
        Parishes::create(['name' => 'Biruaca', 'id_municipalities' => '30']);
        Parishes::create(['name' => 'Bruzual', 'id_municipalities' => '31']);
        Parishes::create(['name' => 'Mantecal', 'id_municipalities' => '31']);
        Parishes::create(['name' => 'Quintero', 'id_municipalities' => '31']);
        Parishes::create(['name' => 'Rincón Hondo', 'id_municipalities' => '31']);
        Parishes::create(['name' => 'San Vicente', 'id_municipalities' => '31']);
        Parishes::create(['name' => 'Guasdualito', 'id_municipalities' => '32']);
        Parishes::create(['name' => 'Aramendi', 'id_municipalities' => '32']);
        Parishes::create(['name' => 'El Amparo', 'id_municipalities' => '32']);
        Parishes::create(['name' => 'San Camilo', 'id_municipalities' => '32']);
        Parishes::create(['name' => 'Urdaneta', 'id_municipalities' => '32']);
        Parishes::create(['name' => 'San Juan de Payara', 'id_municipalities' => '33']);
        Parishes::create(['name' => 'Codazzi', 'id_municipalities' => '33']);
        Parishes::create(['name' => 'Cunaviche', 'id_municipalities' => '33']);
        Parishes::create(['name' => 'Elorza', 'id_municipalities' => '34']);
        Parishes::create(['name' => 'La Trinidad', 'id_municipalities' => '34']);
        Parishes::create(['name' => 'San Fernando', 'id_municipalities' => '35']);
        Parishes::create(['name' => 'El Recreo', 'id_municipalities' => '35']);
        Parishes::create(['name' => 'Peñalver', 'id_municipalities' => '35']);
        Parishes::create(['name' => 'San Rafael de Atamaica', 'id_municipalities' => '35']);
        Parishes::create(['name' => 'Pedro José Ovalles', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'Joaquín Crespo', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'José Casanova Godoy', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'Madre María de San José', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'Andrés Eloy Blanco', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'Los Tacarigua', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'Las Delicias', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'Choroní', 'id_municipalities' => '36']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '37']);
        Parishes::create(['name' => 'Camatagua', 'id_municipalities' => '38']);
        Parishes::create(['name' => 'Carmen de Cura', 'id_municipalities' => '38']);
        Parishes::create(['name' => 'Santa Rita', 'id_municipalities' => '39']);
        Parishes::create(['name' => 'Francisco de Miranda', 'id_municipalities' => '39']);
        Parishes::create(['name' => 'Moseñor Feliciano González', 'id_municipalities' => '39']);
        Parishes::create(['name' => 'Santa Cruz', 'id_municipalities' => '40']);
        Parishes::create(['name' => 'José Félix Ribas', 'id_municipalities' => '41']);
        Parishes::create(['name' => 'Castor Nieves Ríos', 'id_municipalities' => '41']);
        Parishes::create(['name' => 'Las Guacamayas', 'id_municipalities' => '41']);
        Parishes::create(['name' => 'Pao de Zárate', 'id_municipalities' => '41']);
        Parishes::create(['name' => 'Zuata', 'id_municipalities' => '41']);
        Parishes::create(['name' => 'José Rafael Revenga', 'id_municipalities' => '42']);
        Parishes::create(['name' => 'Palo Negro', 'id_municipalities' => '43']);
        Parishes::create(['name' => 'San Martín de Porres', 'id_municipalities' => '43']);
        Parishes::create(['name' => 'El Limón', 'id_municipalities' => '44']);
        Parishes::create(['name' => 'Caña de Azúcar', 'id_municipalities' => '44']);
        Parishes::create(['name' => 'Ocumare de la Costa', 'id_municipalities' => '45']);
        Parishes::create(['name' => 'San Casimiro', 'id_municipalities' => '46']);
        Parishes::create(['name' => 'Güiripa', 'id_municipalities' => '46']);
        Parishes::create(['name' => 'Ollas de Caramacate', 'id_municipalities' => '46']);
        Parishes::create(['name' => 'Valle Morín', 'id_municipalities' => '46']);
        Parishes::create(['name' => 'San Sebastían', 'id_municipalities' => '47']);
        Parishes::create(['name' => 'Turmero', 'id_municipalities' => '48']);
        Parishes::create(['name' => 'Arevalo Aponte', 'id_municipalities' => '48']);
        Parishes::create(['name' => 'Chuao', 'id_municipalities' => '48']);
        Parishes::create(['name' => 'Samán de Güere', 'id_municipalities' => '48']);
        Parishes::create(['name' => 'Alfredo Pacheco Miranda', 'id_municipalities' => '48']);
        Parishes::create(['name' => 'Santos Michelena', 'id_municipalities' => '49']);
        Parishes::create(['name' => 'Tiara', 'id_municipalities' => '49']);
        Parishes::create(['name' => 'Cagua', 'id_municipalities' => '50']);
        Parishes::create(['name' => 'Bella Vista', 'id_municipalities' => '50']);
        Parishes::create(['name' => 'Tovar', 'id_municipalities' => '51']);
        Parishes::create(['name' => 'Urdaneta', 'id_municipalities' => '52']);
        Parishes::create(['name' => 'Las Peñitas', 'id_municipalities' => '52']);
        Parishes::create(['name' => 'San Francisco de Cara', 'id_municipalities' => '52']);
        Parishes::create(['name' => 'Taguay', 'id_municipalities' => '52']);
        Parishes::create(['name' => 'Zamora', 'id_municipalities' => '53']);
        Parishes::create(['name' => 'Magdaleno', 'id_municipalities' => '53']);
        Parishes::create(['name' => 'San Francisco de Asís', 'id_municipalities' => '53']);
        Parishes::create(['name' => 'Valles de Tucutunemo', 'id_municipalities' => '53']);
        Parishes::create(['name' => 'Augusto Mijares', 'id_municipalities' => '53']);
        Parishes::create(['name' => 'Sabaneta', 'id_municipalities' => '54']);
        Parishes::create(['name' => 'Juan Antonio Rodríguez Domínguez', 'id_municipalities' => '54']);
        Parishes::create(['name' => 'El Cantón', 'id_municipalities' => '55']);
        Parishes::create(['name' => 'Santa Cruz de Guacas', 'id_municipalities' => '55']);
        Parishes::create(['name' => 'Puerto Vivas', 'id_municipalities' => '55']);
        Parishes::create(['name' => 'Ticoporo', 'id_municipalities' => '56']);
        Parishes::create(['name' => 'Nicolás Pulido', 'id_municipalities' => '56']);
        Parishes::create(['name' => 'Andrés Bello', 'id_municipalities' => '56']);
        Parishes::create(['name' => 'Arismendi', 'id_municipalities' => '57']);
        Parishes::create(['name' => 'Guadarrama', 'id_municipalities' => '57']);
        Parishes::create(['name' => 'La Unión', 'id_municipalities' => '57']);
        Parishes::create(['name' => 'San Antonio', 'id_municipalities' => '57']);
        Parishes::create(['name' => 'Barinas', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Alberto Arvelo Larriva', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'San Silvestre', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Santa Inés', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Santa Lucía', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Torumos', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'El Carmen', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Rómulo Betancourt', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Corazón de Jesús', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Ramón Ignacio Méndez', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Alto Barinas', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Manuel Palacio Fajardo', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Juan Antonio Rodríguez Domínguez', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Dominga Ortiz de Páez', 'id_municipalities' => '58']);
        Parishes::create(['name' => 'Barinitas', 'id_municipalities' => '	59']);
        Parishes::create(['name' => 'Altamira de Cáceres', 'id_municipalities' => '59']);
        Parishes::create(['name' => 'Calderas', 'id_municipalities' => '59']);
        Parishes::create(['name' => 'Barrancas', 'id_municipalities' => '60']);
        Parishes::create(['name' => 'El Socorro', 'id_municipalities' => '60']);
        Parishes::create(['name' => 'Mazparrito', 'id_municipalities' => '60']);
        Parishes::create(['name' => 'Santa Bárbara', 'id_municipalities' => '61']);
        Parishes::create(['name' => 'Pedro Briceño Méndez', 'id_municipalities' => '61']);
        Parishes::create(['name' => 'Ramón Ignacio Méndez', 'id_municipalities' => '61']);
        Parishes::create(['name' => 'José Ignacio del Pumar', 'id_municipalities' => '61']);
        Parishes::create(['name' => 'Obispos', 'id_municipalities' => '62']);
        Parishes::create(['name' => 'Guasimitos', 'id_municipalities' => '62']);
        Parishes::create(['name' => 'El Real', 'id_municipalities' => '62']);
        Parishes::create(['name' => 'La Luz', 'id_municipalities' => '62']);
        Parishes::create(['name' => 'Ciudad Bolívia', 'id_municipalities' => '63']);
        Parishes::create(['name' => 'José Ignacio Briceño', 'id_municipalities' => '63']);
        Parishes::create(['name' => 'José Félix Ribas', 'id_municipalities' => '63']);
        Parishes::create(['name' => 'Páez', 'id_municipalities' => '63']);
        Parishes::create(['name' => 'Libertad', 'id_municipalities' => '64']);
        Parishes::create(['name' => 'Dolores', 'id_municipalities' => '64']);
        Parishes::create(['name' => 'Santa Rosa', 'id_municipalities' => '64']);
        Parishes::create(['name' => 'Palacio Fajardo', 'id_municipalities' => '64']);
        Parishes::create(['name' => 'Ciudad de Nutrias', 'id_municipalities' => '65']);
        Parishes::create(['name' => 'El Regalo', 'id_municipalities' => '65']);
        Parishes::create(['name' => 'Puerto Nutrias', 'id_municipalities' => '65']);
        Parishes::create(['name' => 'Santa Catalina', 'id_municipalities' => '65']);
        Parishes::create(['name' => 'Cachamay', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Chirica', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Dalla Costa', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Once de Abril', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Simón Bolívar', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Unare', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Universidad', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Vista al Sol', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Pozo Verde', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Yocoima', 'id_municipalities' => '66']);
        Parishes::create(['name' => '5 de Julio', 'id_municipalities' => '66']);
        Parishes::create(['name' => 'Cedeño', 'id_municipalities' => '67']);
        Parishes::create(['name' => 'Altagracia', 'id_municipalities' => '67']);
        Parishes::create(['name' => 'Ascensión Farreras', 'id_municipalities' => '67']);
        Parishes::create(['name' => 'Guaniamo', 'id_municipalities' => '67']);
        Parishes::create(['name' => 'La Urbana', 'id_municipalities' => '67']);
        Parishes::create(['name' => 'Pijiguaos', 'id_municipalities' => '67']);
        Parishes::create(['name' => 'El Callao', 'id_municipalities' => '68']);
        Parishes::create(['name' => 'Gran Sabana', 'id_municipalities' => '69']);
        Parishes::create(['name' => 'Ikabarú', 'id_municipalities' => '69']);
        Parishes::create(['name' => 'Catedral', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'Zea', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'Orinoco', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'José Antonio Páez', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'Marhuanta', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'Agua Salada', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'Vista Hermosa', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'La Sabanita', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'Panapana', 'id_municipalities' => '70']);
        Parishes::create(['name' => 'Andrés Eloy Blanco', 'id_municipalities' => '71']);
        Parishes::create(['name' => 'Pedro Cova', 'id_municipalities' => '71']);
        Parishes::create(['name' => 'Raúl Leoni', 'id_municipalities' => '72']);
        Parishes::create(['name' => 'Barceloneta', 'id_municipalities' => '72']);
        Parishes::create(['name' => 'Santa Bárbara', 'id_municipalities' => '72']);
        Parishes::create(['name' => 'San Francisco', 'id_municipalities' => '72']);
        Parishes::create(['name' => 'Roscio', 'id_municipalities' => '73']);
        Parishes::create(['name' => 'Salóm', 'id_municipalities' => '73']);
        Parishes::create(['name' => 'Sifontes', 'id_municipalities' => '74']);
        Parishes::create(['name' => 'Dalla Costa', 'id_municipalities' => '74']);
        Parishes::create(['name' => 'San Isidro', 'id_municipalities' => '74']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '75']);
        Parishes::create(['name' => 'Aripao', 'id_municipalities' => '75']);
        Parishes::create(['name' => 'Guarataro', 'id_municipalities' => '75']);
        Parishes::create(['name' => 'Las Majadas', 'id_municipalities' => '75']);
        Parishes::create(['name' => 'Moitaco', 'id_municipalities' => '75']);
        Parishes::create(['name' => 'Padre Pedro Chien', 'id_municipalities' => '76']);
        Parishes::create(['name' => 'Río Grande', 'id_municipalities' => '76']);
        Parishes::create(['name' => 'Bejuma', 'id_municipalities' => '77']);
        Parishes::create(['name' => 'Canoabo', 'id_municipalities' => '77']);
        Parishes::create(['name' => 'Simón Bolívar', 'id_municipalities' => '77']);
        Parishes::create(['name' => 'Güigüe', 'id_municipalities' => '78']);
        Parishes::create(['name' => 'Carabobo', 'id_municipalities' => '78']);
        Parishes::create(['name' => 'Tacarigua', 'id_municipalities' => '78']);
        Parishes::create(['name' => 'Mariara', 'id_municipalities' => '79']);
        Parishes::create(['name' => 'Aguas Calientes', 'id_municipalities' => '79']);
        Parishes::create(['name' => 'Ciudad Alianza', 'id_municipalities' => '80']);
        Parishes::create(['name' => 'Guacara', 'id_municipalities' => '80']);
        Parishes::create(['name' => 'Yagua', 'id_municipalities' => '80']);
        Parishes::create(['name' => 'Morón', 'id_municipalities' => '81']);
        Parishes::create(['name' => 'Yagua', 'id_municipalities' => '81']);
        Parishes::create(['name' => 'Tocuyito', 'id_municipalities' => '82']);
        Parishes::create(['name' => 'Independencia', 'id_municipalities' => '82']);
        Parishes::create(['name' => 'Los Guayos', 'id_municipalities' => '83']);
        Parishes::create(['name' => 'Miranda', 'id_municipalities' => '84']);
        Parishes::create(['name' => 'Montalbán', 'id_municipalities' => '85']);
        Parishes::create(['name' => 'Naguanagua', 'id_municipalities' => '86']);
        Parishes::create(['name' => 'Bartolomé Salóm', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'Democracia', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'Fraternidad', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'Goaigoaza', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'Juan José Flores', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'Unión', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'Borburata', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'Patanemo', 'id_municipalities' => '87']);
        Parishes::create(['name' => 'San Diego', 'id_municipalities' => '88']);
        Parishes::create(['name' => 'San Joaquín', 'id_municipalities' => '89']);
        Parishes::create(['name' => 'Candelaria', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'Catedral', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'El Socorro', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'Miguel Peña', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'Rafael Urdaneta', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'San Blas', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'San José', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'Santa Rosa', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'Negro Primero', 'id_municipalities' => '90']);
        Parishes::create(['name' => 'Cojedes', 'id_municipalities' => '91']);
        Parishes::create(['name' => 'Juan de Mata Suárez', 'id_municipalities' => '91']);
        Parishes::create(['name' => 'Tinaquillo', 'id_municipalities' => '92']);
        Parishes::create(['name' => 'El Baúl', 'id_municipalities' => '93']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '93']);
        Parishes::create(['name' => 'La Aguadita', 'id_municipalities' => '94']);
        Parishes::create(['name' => 'Macapo', 'id_municipalities' => '94']);
        Parishes::create(['name' => 'El Pao', 'id_municipalities' => '95']);
        Parishes::create(['name' => 'El Amparo', 'id_municipalities' => '96']);
        Parishes::create(['name' => 'Libertad de Cojedes', 'id_municipalities' => '96']);
        Parishes::create(['name' => 'Rómulo Gallegos', 'id_municipalities' => '97']);
        Parishes::create(['name' => 'San Carlos de Austria', 'id_municipalities' => '98']);
        Parishes::create(['name' => 'Juan Ángel Bravo', 'id_municipalities' => '98']);
        Parishes::create(['name' => 'Manuel Manrique', 'id_municipalities' => '98']);
        Parishes::create(['name' => 'General en Jefe José Laurencio Silva', 'id_municipalities' => '99']);
        Parishes::create(['name' => 'Curiapo', 'id_municipalities' => '100']);
        Parishes::create(['name' => 'Almirante Luis Brión', 'id_municipalities' => '100']);
        Parishes::create(['name' => 'Francisco Aniceto Lugo', 'id_municipalities' => '100']);
        Parishes::create(['name' => 'Manuel Renaud', 'id_municipalities' => '100']);
        Parishes::create(['name' => 'Padre Barral', 'id_municipalities' => '100']);
        Parishes::create(['name' => 'Santos de Abelgas', 'id_municipalities' => '100']);
        Parishes::create(['name' => 'Imataca', 'id_municipalities' => '101']);
        Parishes::create(['name' => 'Cinco de Julio', 'id_municipalities' => '101']);
        Parishes::create(['name' => 'Juan Bautista Arismendi', 'id_municipalities' => '101']);
        Parishes::create(['name' => 'Manuel Piar', 'id_municipalities' => '101']);
        Parishes::create(['name' => 'Rómulo Gallegos', 'id_municipalities' => '101']);
        Parishes::create(['name' => 'Pedernales', 'id_municipalities' => '102']);
        Parishes::create(['name' => 'Luis Beltrán Prieto Figueroa', 'id_municipalities' => '102']);
        Parishes::create(['name' => 'San José (Delta Amacuro)', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'José Vidal Marcano', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'Juan Millán', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'Leonardo Ruíz Pineda', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'Mariscal Antonio José de Sucre', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'Monseñor Argimiro García', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'San Rafael (Delta Amacuro)', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'Virgen del Valle', 'id_municipalities' => '103']);
        Parishes::create(['name' => 'Clarines', 'id_municipalities' => '10']);
        Parishes::create(['name' => 'Guanape', 'id_municipalities' => '10']);
        Parishes::create(['name' => 'Sabana de Uchire', 'id_municipalities' => '10']);
        Parishes::create(['name' => 'Capadare', 'id_municipalities' => '104']);
        Parishes::create(['name' => 'La Pastora', 'id_municipalities' => '104']);
        Parishes::create(['name' => 'Libertador', 'id_municipalities' => '104']);
        Parishes::create(['name' => 'San Juan de los Cayos', 'id_municipalities' => '104']);
        Parishes::create(['name' => 'Aracua', 'id_municipalities' => '105']);
        Parishes::create(['name' => 'La Peña', 'id_municipalities' => '105']);
        Parishes::create(['name' => 'San Luis', 'id_municipalities' => '105']);
        Parishes::create(['name' => 'Bariro', 'id_municipalities' => '106']);
        Parishes::create(['name' => 'Borojó', 'id_municipalities' => '106']);
        Parishes::create(['name' => 'Capatárida', 'id_municipalities' => '106']);
        Parishes::create(['name' => 'Guajiro', 'id_municipalities' => '106']);
        Parishes::create(['name' => 'Seque', 'id_municipalities' => '106']);
        Parishes::create(['name' => 'Zazárida', 'id_municipalities' => '106']);
        Parishes::create(['name' => 'Valle de Eroa', 'id_municipalities' => '106']);
        Parishes::create(['name' => 'Cacique Manaure', 'id_municipalities' => '107']);
        Parishes::create(['name' => 'Norte', 'id_municipalities' => '108']);
        Parishes::create(['name' => 'Carirubana', 'id_municipalities' => '108']);
        Parishes::create(['name' => 'Santa Ana', 'id_municipalities' => '108']);
        Parishes::create(['name' => 'Urbana Punta Cardón', 'id_municipalities' => '108']);
        Parishes::create(['name' => 'La Vela de Coro', 'id_municipalities' => '109']);
        Parishes::create(['name' => 'Acurigua', 'id_municipalities' => '109']);
        Parishes::create(['name' => 'Guaibacoa', 'id_municipalities' => '109']);
        Parishes::create(['name' => 'Las Calderas', 'id_municipalities' => '109']);
        Parishes::create(['name' => 'Macoruca', 'id_municipalities' => '109']);
        Parishes::create(['name' => 'Dabajuro', 'id_municipalities' => '110']);
        Parishes::create(['name' => 'Agua Clara', 'id_municipalities' => '111']);
        Parishes::create(['name' => 'Avaria', 'id_municipalities' => '111']);
        Parishes::create(['name' => 'Pedregal', 'id_municipalities' => '111']);
        Parishes::create(['name' => 'Piedra Grande', 'id_municipalities' => '111']);
        Parishes::create(['name' => 'Purureche', 'id_municipalities' => '111']);
        Parishes::create(['name' => 'Adaure', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'Adícora', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'Baraived', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'Buena Vista', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'Jadacaquiva', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'El Vínculo', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'El Hato', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'Moruy', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'Pueblo Nuevo', 'id_municipalities' => '112']);
        Parishes::create(['name' => 'Agua Larga', 'id_municipalities' => '113']);
        Parishes::create(['name' => 'El Paují', 'id_municipalities' => '113']);
        Parishes::create(['name' => 'Independencia', 'id_municipalities' => '113']);
        Parishes::create(['name' => 'Mapararí', 'id_municipalities' => '113']);
        Parishes::create(['name' => 'Agua Linda', 'id_municipalities' => '114']);
        Parishes::create(['name' => 'Araurima', 'id_municipalities' => '114']);
        Parishes::create(['name' => 'Jacura', 'id_municipalities' => '114']);
        Parishes::create(['name' => 'Tucacas', 'id_municipalities' => '115']);
        Parishes::create(['name' => 'Boca de Aroa', 'id_municipalities' => '115']);
        Parishes::create(['name' => 'Los Taques', 'id_municipalities' => '116']);
        Parishes::create(['name' => 'Judibana', 'id_municipalities' => '116']);
        Parishes::create(['name' => 'Mene de Mauroa', 'id_municipalities' => '117']);
        Parishes::create(['name' => 'San Félix', 'id_municipalities' => '117']);
        Parishes::create(['name' => 'Casigua', 'id_municipalities' => '117']);
        Parishes::create(['name' => 'Guzmán Guillermo', 'id_municipalities' => '118']);
        Parishes::create(['name' => 'Mitare', 'id_municipalities' => '118']);
        Parishes::create(['name' => 'Río Seco', 'id_municipalities' => '118']);
        Parishes::create(['name' => 'Sabaneta', 'id_municipalities' => '118']);
        Parishes::create(['name' => 'San Antonio', 'id_municipalities' => '118']);
        Parishes::create(['name' => 'San Gabriel', 'id_municipalities' => '118']);
        Parishes::create(['name' => 'Santa Ana', 'id_municipalities' => '118']);
        Parishes::create(['name' => 'Boca del Tocuyo', 'id_municipalities' => '119']);
        Parishes::create(['name' => 'Chichiriviche', 'id_municipalities' => '119']);
        Parishes::create(['name' => 'Tocuyo de la Costa', 'id_municipalities' => '119']);
        Parishes::create(['name' => 'Palmasola', 'id_municipalities' => '120']);
        Parishes::create(['name' => 'Cabure', 'id_municipalities' => '121']);
        Parishes::create(['name' => 'Colina', 'id_municipalities' => '121']);
        Parishes::create(['name' => 'Curimagua', 'id_municipalities' => '121']);
        Parishes::create(['name' => 'San José de la Costa', 'id_municipalities' => '122']);
        Parishes::create(['name' => 'Píritu', 'id_municipalities' => '122']);
        Parishes::create(['name' => 'San Francisco', 'id_municipalities' => '123']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '124']);
        Parishes::create(['name' => 'Pecaya', 'id_municipalities' => '124']);
        Parishes::create(['name' => 'Tocópero', 'id_municipalities' => '125']);
        Parishes::create(['name' => 'El Charal', 'id_municipalities' => '126']);
        Parishes::create(['name' => 'Las Vegas del Tuy', 'id_municipalities' => '126']);
        Parishes::create(['name' => 'Santa Cruz de Bucaral', 'id_municipalities' => '126']);
        Parishes::create(['name' => 'Bruzual', 'id_municipalities' => '127']);
        Parishes::create(['name' => 'Urumaco', 'id_municipalities' => '127']);
        Parishes::create(['name' => 'Puerto Cumarebo', 'id_municipalities' => '128']);
        Parishes::create(['name' => 'La Ciénaga', 'id_municipalities' => '128']);
        Parishes::create(['name' => 'La Soledad', 'id_municipalities' => '128']);
        Parishes::create(['name' => 'Pueblo Cumarebo', 'id_municipalities' => '128']);
        Parishes::create(['name' => 'Zazárida', 'id_municipalities' => '128']);
        Parishes::create(['name' => 'Churuguara', 'id_municipalities' => '113']);
        Parishes::create(['name' => 'Camaguán', 'id_municipalities' => '129']);
        Parishes::create(['name' => 'Puerto Miranda', 'id_municipalities' => '129']);
        Parishes::create(['name' => 'Uverito', 'id_municipalities' => '129']);
        Parishes::create(['name' => 'Chaguaramas', 'id_municipalities' => '130']);
        Parishes::create(['name' => 'El Socorro', 'id_municipalities' => '131']);
        Parishes::create(['name' => 'Tucupido', 'id_municipalities' => '132']);
        Parishes::create(['name' => 'San Rafael de Laya', 'id_municipalities' => '132']);
        Parishes::create(['name' => 'Altagracia de Orituco', 'id_municipalities' => '133']);
        Parishes::create(['name' => 'San Rafael de Orituco', 'id_municipalities' => '133']);
        Parishes::create(['name' => 'San Francisco Javier de Lezama', 'id_municipalities' => '133']);
        Parishes::create(['name' => 'Paso Real de Macaira', 'id_municipalities' => '133']);
        Parishes::create(['name' => 'Carlos Soublette', 'id_municipalities' => '133']);
        Parishes::create(['name' => 'San Francisco de Macaira', 'id_municipalities' => '133']);
        Parishes::create(['name' => 'Libertad de Orituco', 'id_municipalities' => '133']);
        Parishes::create(['name' => 'Cantaclaro', 'id_municipalities' => '134']);
        Parishes::create(['name' => 'San Juan de los Morros', 'id_municipalities' => '134']);
        Parishes::create(['name' => 'Parapara', 'id_municipalities' => '134']);
        Parishes::create(['name' => 'El Sombrero', 'id_municipalities' => '135']);
        Parishes::create(['name' => 'Sosa', 'id_municipalities' => '135']);
        Parishes::create(['name' => 'Las Mercedes', 'id_municipalities' => '136']);
        Parishes::create(['name' => 'Cabruta', 'id_municipalities' => '136']);
        Parishes::create(['name' => 'Santa Rita de Manapire', 'id_municipalities' => '136']);
        Parishes::create(['name' => 'Valle de la Pascua', 'id_municipalities' => '137']);
        Parishes::create(['name' => 'Espino', 'id_municipalities' => '137']);
        Parishes::create(['name' => 'San José de Unare', 'id_municipalities' => '138']);
        Parishes::create(['name' => 'Zaraza', 'id_municipalities' => '138']);
        Parishes::create(['name' => 'San José de Tiznados', 'id_municipalities' => '139']);
        Parishes::create(['name' => 'San Francisco de Tiznados', 'id_municipalities' => '139']);
        Parishes::create(['name' => 'San Lorenzo de Tiznados', 'id_municipalities' => '139']);
        Parishes::create(['name' => 'Ortiz', 'id_municipalities' => '139']);
        Parishes::create(['name' => 'Guayabal', 'id_municipalities' => '140']);
        Parishes::create(['name' => 'Cazorla', 'id_municipalities' => '140']);
        Parishes::create(['name' => 'San José de Guaribe', 'id_municipalities' => '141']);
        Parishes::create(['name' => 'Uveral', 'id_municipalities' => '141']);
        Parishes::create(['name' => 'Santa María de Ipire', 'id_municipalities' => '142']);
        Parishes::create(['name' => 'Altamira', 'id_municipalities' => '142']);
        Parishes::create(['name' => 'El Calvario', 'id_municipalities' => '143']);
        Parishes::create(['name' => 'El Rastro', 'id_municipalities' => '143']);
        Parishes::create(['name' => 'Guardatinajas', 'id_municipalities' => '143']);
        Parishes::create(['name' => 'Capital Urbana Calabozo', 'id_municipalities' => '143']);
        Parishes::create(['name' => 'Quebrada Honda de Guache', 'id_municipalities' => '144']);
        Parishes::create(['name' => 'Pío Tamayo', 'id_municipalities' => '144']);
        Parishes::create(['name' => 'Yacambú', 'id_municipalities' => '144']);
        Parishes::create(['name' => 'Fréitez', 'id_municipalities' => '145']);
        Parishes::create(['name' => 'José María Blanco', 'id_municipalities' => '145']);
        Parishes::create(['name' => 'Catedral', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Concepción', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'El Cují', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Juan de Villegas', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Santa Rosa', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Tamaca', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Unión', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Aguedo Felipe Alvarado', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Buena Vista', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Juárez', 'id_municipalities' => '146']);
        Parishes::create(['name' => 'Juan Bautista Rodríguez', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'Cuara', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'Diego de Lozada', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'Paraíso de San José', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'San Miguel', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'Tintorero', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'José Bernardo Dorante', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'Coronel Mariano Peraza ', 'id_municipalities' => '147']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'Anzoátegui', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'Guarico', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'Hilario Luna y Luna', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'Humocaro Alto', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'Humocaro Bajo', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'La Candelaria', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'Morán', 'id_municipalities' => '148']);
        Parishes::create(['name' => 'Cabudare', 'id_municipalities' => '149']);
        Parishes::create(['name' => 'José Gregorio Bastidas', 'id_municipalities' => '149']);
        Parishes::create(['name' => 'Agua Viva', 'id_municipalities' => '149']);
        Parishes::create(['name' => 'Sarare', 'id_municipalities' => '150']);
        Parishes::create(['name' => 'Buría', 'id_municipalities' => '150']);
        Parishes::create(['name' => 'Gustavo Vegas León', 'id_municipalities' => '150']);
        Parishes::create(['name' => 'Trinidad Samuel', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Antonio Díaz', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Camacaro', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Castañeda', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Cecilio Zubillaga', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Chiquinquirá', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'El Blanco', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Espinoza de los Monteros', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Lara', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Las Mercedes', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Manuel Morillo', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Montaña Verde', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Montes de Oca', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Torres', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Heriberto Arroyo', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Reyes Vargas', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Altagracia', 'id_municipalities' => '151']);
        Parishes::create(['name' => 'Siquisique', 'id_municipalities' => '152']);
        Parishes::create(['name' => 'Moroturo', 'id_municipalities' => '152']);
        Parishes::create(['name' => 'San Miguel', 'id_municipalities' => '152']);
        Parishes::create(['name' => 'Xaguas', 'id_municipalities' => '152']);
        Parishes::create(['name' => 'Presidente Betancourt', 'id_municipalities' => '153']);
        Parishes::create(['name' => 'Presidente Páez', 'id_municipalities' => '153']);
        Parishes::create(['name' => 'Presidente Rómulo Gallegos', 'id_municipalities' => '153']);
        Parishes::create(['name' => 'Gabriel Picón González', 'id_municipalities' => '153']);
        Parishes::create(['name' => 'Héctor Amable Mora', 'id_municipalities' => '153']);
        Parishes::create(['name' => 'José Nucete Sardi', 'id_municipalities' => '153']);
        Parishes::create(['name' => 'Pulido Méndez', 'id_municipalities' => '153']);
        Parishes::create(['name' => 'La Azulita', 'id_municipalities' => '154']);
        Parishes::create(['name' => 'Santa Cruz de Mora', 'id_municipalities' => '155']);
        Parishes::create(['name' => 'Mesa Bolívar', 'id_municipalities' => '155']);
        Parishes::create(['name' => 'Mesa de Las Palmas', 'id_municipalities' => '155']);
        Parishes::create(['name' => 'Aricagua', 'id_municipalities' => '156']);
        Parishes::create(['name' => 'San Antonio', 'id_municipalities' => '156']);
        Parishes::create(['name' => 'Canagua', 'id_municipalities' => '157']);
        Parishes::create(['name' => 'Capurí', 'id_municipalities' => '157']);
        Parishes::create(['name' => 'Chacantá', 'id_municipalities' => '157']);
        Parishes::create(['name' => 'El Molino', 'id_municipalities' => '157']);
        Parishes::create(['name' => 'Guaimaral', 'id_municipalities' => '157']);
        Parishes::create(['name' => 'Mucutuy', 'id_municipalities' => '157']);
        Parishes::create(['name' => 'Mucuchachí', 'id_municipalities' => '157']);
        Parishes::create(['name' => 'Fernández Peña', 'id_municipalities' => '158']);
        Parishes::create(['name' => 'Matriz', 'id_municipalities' => '158']);
        Parishes::create(['name' => 'Montalbán', 'id_municipalities' => '158']);
        Parishes::create(['name' => 'Acequias', 'id_municipalities' => '158']);
        Parishes::create(['name' => 'Jají', 'id_municipalities' => '158']);
        Parishes::create(['name' => 'La Mesa', 'id_municipalities' => '158']);
        Parishes::create(['name' => 'San José del Sur', 'id_municipalities' => '158']);
        Parishes::create(['name' => 'Tucaní', 'id_municipalities' => '159']);
        Parishes::create(['name' => 'Florencio Ramírez', 'id_municipalities' => '159']);
        Parishes::create(['name' => 'Santo Domingo', 'id_municipalities' => '160']);
        Parishes::create(['name' => 'Las Piedras', 'id_municipalities' => '160']);
        Parishes::create(['name' => 'Guaraque', 'id_municipalities' => '161']);
        Parishes::create(['name' => 'Mesa de Quintero', 'id_municipalities' => '161']);
        Parishes::create(['name' => 'Río Negro', 'id_municipalities' => '161']);
        Parishes::create(['name' => 'Arapuey', 'id_municipalities' => '162']);
        Parishes::create(['name' => 'Palmira', 'id_municipalities' => '162']);
        Parishes::create(['name' => 'San Cristóbal de Torondoy', 'id_municipalities' => '163']);
        Parishes::create(['name' => 'Torondoy', 'id_municipalities' => '163']);
        Parishes::create(['name' => 'Antonio Spinetti Dini', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Arias', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Caracciolo Parra Pérez', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Domingo Peña', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'El Llano', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Gonzalo Picón Febres', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Jacinto Plaza', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Juan Rodríguez Suárez', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Lasso de la Vega', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Mariano Picón Salas', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Milla', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Osuna Rodríguez', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Sagrario', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'El Morro', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Los Nevados', 'id_municipalities' => '164']);
        Parishes::create(['name' => 'Andrés Eloy Blanco', 'id_municipalities' => '165']);
        Parishes::create(['name' => 'La Venta', 'id_municipalities' => '165']);
        Parishes::create(['name' => 'Piñango', 'id_municipalities' => '165']);
        Parishes::create(['name' => 'Timotes', 'id_municipalities' => '165']);
        Parishes::create(['name' => 'Eloy Paredes', 'id_municipalities' => '166']);
        Parishes::create(['name' => 'San Rafael de Alcázar', 'id_municipalities' => '166']);
        Parishes::create(['name' => 'Santa Elena de Arenales', 'id_municipalities' => '166']);
        Parishes::create(['name' => 'Santa María de Caparo', 'id_municipalities' => '167']);
        Parishes::create(['name' => 'Pueblo Llano', 'id_municipalities' => '168']);
        Parishes::create(['name' => 'Cacute', 'id_municipalities' => '169']);
        Parishes::create(['name' => 'La Toma', 'id_municipalities' => '169']);
        Parishes::create(['name' => 'Mucuchíes', 'id_municipalities' => '169']);
        Parishes::create(['name' => 'Mucurubá', 'id_municipalities' => '169']);
        Parishes::create(['name' => 'San Rafael', 'id_municipalities' => '169']);
        Parishes::create(['name' => 'Gerónimo Maldonado', 'id_municipalities' => '170']);
        Parishes::create(['name' => 'Bailadores', 'id_municipalities' => '170']);
        Parishes::create(['name' => 'Tabay', 'id_municipalities' => '171']);
        Parishes::create(['name' => 'Chiguará', 'id_municipalities' => '172']);
        Parishes::create(['name' => 'Estánquez', 'id_municipalities' => '172']);
        Parishes::create(['name' => 'Lagunillas', 'id_municipalities' => '172']);
        Parishes::create(['name' => 'La Trampa', 'id_municipalities' => '172']);
        Parishes::create(['name' => 'Pueblo Nuevo del Sur', 'id_municipalities' => '172']);
        Parishes::create(['name' => 'San Juan', 'id_municipalities' => '172']);
        Parishes::create(['name' => 'El Amparo', 'id_municipalities' => '173']);
        Parishes::create(['name' => 'El Llano', 'id_municipalities' => '173']);
        Parishes::create(['name' => 'San Francisco', 'id_municipalities' => '173']);
        Parishes::create(['name' => 'Tovar', 'id_municipalities' => '173']);
        Parishes::create(['name' => 'Independencia', 'id_municipalities' => '174']);
        Parishes::create(['name' => 'María de la Concepción Palacios Blanco', 'id_municipalities' => '174']);
        Parishes::create(['name' => 'Nueva Bolivia', 'id_municipalities' => '174']);
        Parishes::create(['name' => 'Santa Apolonia', 'id_municipalities' => '174']);
        Parishes::create(['name' => 'Caño El Tigre', 'id_municipalities' => '175']);
        Parishes::create(['name' => 'Zea', 'id_municipalities' => '175']);
        Parishes::create(['name' => 'Aragüita', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'Arévalo González', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'Capaya', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'Caucagua', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'Panaquire', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'Ribas', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'El Café', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'Marizapa', 'id_municipalities' => '176']);
        Parishes::create(['name' => 'Cumbo', 'id_municipalities' => '177']);
        Parishes::create(['name' => 'San José de Barlovento', 'id_municipalities' => '177']);
        Parishes::create(['name' => 'El Cafetal', 'id_municipalities' => '178']);
        Parishes::create(['name' => 'Las Minas', 'id_municipalities' => '178']);
        Parishes::create(['name' => 'Nuestra Señora del Rosario', 'id_municipalities' => '178']);
        Parishes::create(['name' => 'Higuerote', 'id_municipalities' => '179']);
        Parishes::create(['name' => 'Curiepe', 'id_municipalities' => '179']);
        Parishes::create(['name' => 'Tacarigua de Brión', 'id_municipalities' => '179']);
        Parishes::create(['name' => 'Mamporal', 'id_municipalities' => '180']);
        Parishes::create(['name' => 'Carrizal', 'id_municipalities' => '181']);
        Parishes::create(['name' => 'Chacao', 'id_municipalities' => '182']);
        Parishes::create(['name' => 'Charallave', 'id_municipalities' => '183']);
        Parishes::create(['name' => 'Las Brisas', 'id_municipalities' => '183']);
        Parishes::create(['name' => 'El Hatillo', 'id_municipalities' => '184']);
        Parishes::create(['name' => 'Altagracia de la Montaña', 'id_municipalities' => '185']);
        Parishes::create(['name' => 'Cecilio Acosta', 'id_municipalities' => '185']);
        Parishes::create(['name' => 'Los Teques', 'id_municipalities' => '185']);
        Parishes::create(['name' => 'El Jarillo', 'id_municipalities' => '185']);
        Parishes::create(['name' => 'San Pedro', 'id_municipalities' => '185']);
        Parishes::create(['name' => 'Tácata', 'id_municipalities' => '185']);
        Parishes::create(['name' => 'Paracotos', 'id_municipalities' => '185']);
        Parishes::create(['name' => 'Cartanal', 'id_municipalities' => '186']);
        Parishes::create(['name' => 'Santa Teresa del Tuy', 'id_municipalities' => '186']);
        Parishes::create(['name' => 'La Democracia', 'id_municipalities' => '187']);
        Parishes::create(['name' => 'Ocumare del Tuy', 'id_municipalities' => '187']);
        Parishes::create(['name' => 'Santa Bárbara', 'id_municipalities' => '187']);
        Parishes::create(['name' => 'San Antonio de los Altos', 'id_municipalities' => '188']);
        Parishes::create(['name' => 'Río Chico', 'id_municipalities' => '189']);
        Parishes::create(['name' => 'El Guapo', 'id_municipalities' => '189']);
        Parishes::create(['name' => 'Tacarigua de la Laguna', 'id_municipalities' => '189']);
        Parishes::create(['name' => 'Paparo', 'id_municipalities' => '189']);
        Parishes::create(['name' => 'San Fernando del Guapo', 'id_municipalities' => '189']);
        Parishes::create(['name' => 'Santa Lucía del Tuy', 'id_municipalities' => '190']);
        Parishes::create(['name' => 'Cúpira', 'id_municipalities' => '191']);
        Parishes::create(['name' => 'Machurucuto', 'id_municipalities' => '191']);
        Parishes::create(['name' => 'Guarenas', 'id_municipalities' => '192']);
        Parishes::create(['name' => 'San Antonio de Yare', 'id_municipalities' => '193']);
        Parishes::create(['name' => 'San Francisco de Yare', 'id_municipalities' => '193']);
        Parishes::create(['name' => 'Leoncio Martínez', 'id_municipalities' => '194']);
        Parishes::create(['name' => 'Petare', 'id_municipalities' => '194']);
        Parishes::create(['name' => 'Caucagüita', 'id_municipalities' => '194']);
        Parishes::create(['name' => 'Filas de Mariche', 'id_municipalities' => '194']);
        Parishes::create(['name' => 'La Dolorita', 'id_municipalities' => '194']);
        Parishes::create(['name' => 'Cúa', 'id_municipalities' => '195']);
        Parishes::create(['name' => 'Nueva Cúa', 'id_municipalities' => '195']);
        Parishes::create(['name' => 'Guatire', 'id_municipalities' => '196']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '196']);
        Parishes::create(['name' => 'San Antonio de Maturín', 'id_municipalities' => '197']);
        Parishes::create(['name' => 'San Francisco de Maturín', 'id_municipalities' => '197']);
        Parishes::create(['name' => 'Aguasay', 'id_municipalities' => '198']);
        Parishes::create(['name' => 'Caripito', 'id_municipalities' => '199']);
        Parishes::create(['name' => 'El Guácharo', 'id_municipalities' => '200']);
        Parishes::create(['name' => 'La Guanota', 'id_municipalities' => '200']);
        Parishes::create(['name' => 'Sabana de Piedra', 'id_municipalities' => '200']);
        Parishes::create(['name' => 'San Agustín', 'id_municipalities' => '200']);
        Parishes::create(['name' => 'Teresen', 'id_municipalities' => '200']);
        Parishes::create(['name' => 'Caripe', 'id_municipalities' => '200']);
        Parishes::create(['name' => 'Areo', 'id_municipalities' => '201']);
        Parishes::create(['name' => 'Capital Cedeño', 'id_municipalities' => '201']);
        Parishes::create(['name' => 'San Félix de Cantalicio', 'id_municipalities' => '201']);
        Parishes::create(['name' => 'Viento Fresco', 'id_municipalities' => '201']);
        Parishes::create(['name' => 'El Tejero', 'id_municipalities' => '202']);
        Parishes::create(['name' => 'Punta de Mata', 'id_municipalities' => '202']);
        Parishes::create(['name' => 'Chaguaramas', 'id_municipalities' => '203']);
        Parishes::create(['name' => 'Las Alhuacas', 'id_municipalities' => '203']);
        Parishes::create(['name' => 'Tabasca', 'id_municipalities' => '203']);
        Parishes::create(['name' => 'Temblador', 'id_municipalities' => '203']);
        Parishes::create(['name' => 'Alto de los Godos', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'Boquerón', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'Las Cocuizas', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'La Cruz', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'San Simón', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'El Corozo', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'El Furrial', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'Jusepín', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'La Pica', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'San Vicente', 'id_municipalities' => '204']);
        Parishes::create(['name' => 'Aparicio', 'id_municipalities' => '205']);
        Parishes::create(['name' => 'Aragua de Maturín', 'id_municipalities' => '205']);
        Parishes::create(['name' => 'Chaguamal', 'id_municipalities' => '205']);
        Parishes::create(['name' => 'El Pinto', 'id_municipalities' => '205']);
        Parishes::create(['name' => 'Guanaguana', 'id_municipalities' => '205']);
        Parishes::create(['name' => 'La Toscana', 'id_municipalities' => '205']);
        Parishes::create(['name' => 'Taguaya', 'id_municipalities' => '205']);
        Parishes::create(['name' => 'Cachipo', 'id_municipalities' => '206']);
        Parishes::create(['name' => 'Quiriquire', 'id_municipalities' => '206']);
        Parishes::create(['name' => 'Santa Bárbara', 'id_municipalities' => '207']);
        Parishes::create(['name' => 'Barrancas', 'id_municipalities' => '208']);
        Parishes::create(['name' => 'Los Barrancos de Fajardo', 'id_municipalities' => '208']);
        Parishes::create(['name' => 'Uracoa', 'id_municipalities' => '209']);
        Parishes::create(['name' => 'Antolín del Campo', 'id_municipalities' => '210']);
        Parishes::create(['name' => 'Arismendi', 'id_municipalities' => '211']);
        Parishes::create(['name' => 'García', 'id_municipalities' => '212']);
        Parishes::create(['name' => 'Francisco Fajardo', 'id_municipalities' => '212']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '213']);
        Parishes::create(['name' => 'Guevara', 'id_municipalities' => '213']);
        Parishes::create(['name' => 'Matasiete', 'id_municipalities' => '213']);
        Parishes::create(['name' => 'Santa Ana', 'id_municipalities' => '213']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '213']);
        Parishes::create(['name' => 'Aguirre', 'id_municipalities' => '214']);
        Parishes::create(['name' => 'Maneiro', 'id_municipalities' => '214']);
        Parishes::create(['name' => 'Adrián', 'id_municipalities' => '215']);
        Parishes::create(['name' => 'Juan Griego', 'id_municipalities' => '215']);
        Parishes::create(['name' => 'Yaguaraparo', 'id_municipalities' => '215']);
        Parishes::create(['name' => 'Porlamar', 'id_municipalities' => '216']);
        Parishes::create(['name' => 'San Francisco de Macanao', 'id_municipalities' => '217']);
        Parishes::create(['name' => 'Boca de Río', 'id_municipalities' => '217']);
        Parishes::create(['name' => 'Tubores', 'id_municipalities' => '218']);
        Parishes::create(['name' => 'Los Baleales', 'id_municipalities' => '218']);
        Parishes::create(['name' => 'Vicente Fuentes', 'id_municipalities' => '219']);
        Parishes::create(['name' => 'Villalba', 'id_municipalities' => '219']);
        Parishes::create(['name' => 'San Juan Bautista', 'id_municipalities' => '220']);
        Parishes::create(['name' => 'Zabala', 'id_municipalities' => '220']);
        Parishes::create(['name' => 'Capital Araure', 'id_municipalities' => '222']);
        Parishes::create(['name' => 'Río Acarigua', 'id_municipalities' => '222']);
        Parishes::create(['name' => 'Capital Esteller', 'id_municipalities' => '223']);
        Parishes::create(['name' => 'Uveral', 'id_municipalities' => '223']);
        Parishes::create(['name' => 'Guanare', 'id_municipalities' => '224']);
        Parishes::create(['name' => 'Córdoba', 'id_municipalities' => '224']);
        Parishes::create(['name' => 'San José de la Montaña', 'id_municipalities' => '224']);
        Parishes::create(['name' => 'San Juan de Guanaguanare', 'id_municipalities' => '224']);
        Parishes::create(['name' => 'Virgen de la Coromoto', 'id_municipalities' => '224']);
        Parishes::create(['name' => 'Guanarito', 'id_municipalities' => '225']);
        Parishes::create(['name' => 'Trinidad de la Capilla', 'id_municipalities' => '225']);
        Parishes::create(['name' => 'Divina Pastora', 'id_municipalities' => '225']);
        Parishes::create(['name' => 'Monseñor José Vicente de Unda', 'id_municipalities' => '226']);
        Parishes::create(['name' => 'Peña Blanca', 'id_municipalities' => '226']);
        Parishes::create(['name' => 'Capital Ospino', 'id_municipalities' => '227']);
        Parishes::create(['name' => 'Aparición', 'id_municipalities' => '227']);
        Parishes::create(['name' => 'La Estación', 'id_municipalities' => '227']);
        Parishes::create(['name' => 'Páez', 'id_municipalities' => '228']);
        Parishes::create(['name' => 'Payara', 'id_municipalities' => '228']);
        Parishes::create(['name' => 'Pimpinela', 'id_municipalities' => '228']);
        Parishes::create(['name' => 'Ramón Peraza', 'id_municipalities' => '228']);
        Parishes::create(['name' => 'Papelón', 'id_municipalities' => '229']);
        Parishes::create(['name' => 'Caño Delgadito', 'id_municipalities' => '229']);
        Parishes::create(['name' => 'San Genaro de Boconoito', 'id_municipalities' => '230']);
        Parishes::create(['name' => 'Antolín Tovar', 'id_municipalities' => '230']);
        Parishes::create(['name' => 'San Rafael de Onoto', 'id_municipalities' => '231']);
        Parishes::create(['name' => 'Santa Fe', 'id_municipalities' => '231']);
        Parishes::create(['name' => 'Thermo Morles', 'id_municipalities' => '231']);
        Parishes::create(['name' => 'Santa Rosalía', 'id_municipalities' => '232']);
        Parishes::create(['name' => 'Florida', 'id_municipalities' => '232']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '233']);
        Parishes::create(['name' => 'Concepción', 'id_municipalities' => '233']);
        Parishes::create(['name' => 'San Rafael de Palo Alzado', 'id_municipalities' => '233']);
        Parishes::create(['name' => 'Uvencio Antonio Velásquez', 'id_municipalities' => '233']);
        Parishes::create(['name' => 'San José de Saguaz', 'id_municipalities' => '233']);
        Parishes::create(['name' => 'Villa Rosa', 'id_municipalities' => '233']);
        Parishes::create(['name' => 'Turén', 'id_municipalities' => '234']);
        Parishes::create(['name' => 'Canelones', 'id_municipalities' => '234']);
        Parishes::create(['name' => 'Santa Cruz', 'id_municipalities' => '234']);
        Parishes::create(['name' => 'San Isidro Labrador', 'id_municipalities' => '234']);
        Parishes::create(['name' => 'Mariño', 'id_municipalities' => '235']);
        Parishes::create(['name' => 'Rómulo Gallegos', 'id_municipalities' => '235']);
        Parishes::create(['name' => 'San José de Aerocuar', 'id_municipalities' => '236']);
        Parishes::create(['name' => 'Tavera Acosta', 'id_municipalities' => '236']);
        Parishes::create(['name' => 'Río Caribe', 'id_municipalities' => '237']);
        Parishes::create(['name' => 'Antonio José de Sucre', 'id_municipalities' => '237']);
        Parishes::create(['name' => 'El Morro de Puerto Santo', 'id_municipalities' => '237']);
        Parishes::create(['name' => 'Puerto Santo', 'id_municipalities' => '237']);
        Parishes::create(['name' => 'San Juan de las Galdonas', 'id_municipalities' => '237']);
        Parishes::create(['name' => 'El Pilar', 'id_municipalities' => '238']);
        Parishes::create(['name' => 'El Rincón', 'id_municipalities' => '238']);
        Parishes::create(['name' => 'General Francisco Antonio Váquez', 'id_municipalities' => '238']);
        Parishes::create(['name' => 'Guaraúnos', 'id_municipalities' => '238']);
        Parishes::create(['name' => 'Tunapuicito', 'id_municipalities' => '238']);
        Parishes::create(['name' => 'Unión', 'id_municipalities' => '238']);
        Parishes::create(['name' => 'Santa Catalina', 'id_municipalities' => '239']);
        Parishes::create(['name' => 'Santa Rosa', 'id_municipalities' => '239']);
        Parishes::create(['name' => 'Santa Teresa', 'id_municipalities' => '239']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '239']);
        Parishes::create(['name' => 'Maracapana', 'id_municipalities' => '239']);
        Parishes::create(['name' => 'Libertad', 'id_municipalities' => '241']);
        Parishes::create(['name' => 'El Paujil', 'id_municipalities' => '241']);
        Parishes::create(['name' => 'Yaguaraparo', 'id_municipalities' => '241']);
        Parishes::create(['name' => 'Cruz Salmerón Acosta', 'id_municipalities' => '242']);
        Parishes::create(['name' => 'Chacopata', 'id_municipalities' => '242']);
        Parishes::create(['name' => 'Manicuare', 'id_municipalities' => '242']);
        Parishes::create(['name' => 'Tunapuy', 'id_municipalities' => '243']);
        Parishes::create(['name' => 'Campo Elías', 'id_municipalities' => '243']);
        Parishes::create(['name' => 'Irapa', 'id_municipalities' => '244']);
        Parishes::create(['name' => 'Campo Claro', 'id_municipalities' => '244']);
        Parishes::create(['name' => 'Maraval', 'id_municipalities' => '244']);
        Parishes::create(['name' => 'San Antonio de Irapa', 'id_municipalities' => '244']);
        Parishes::create(['name' => 'Soro', 'id_municipalities' => '244']);
        Parishes::create(['name' => 'Mejía', 'id_municipalities' => '245']);
        Parishes::create(['name' => 'Cumanacoa', 'id_municipalities' => '246']);
        Parishes::create(['name' => 'Arenas', 'id_municipalities' => '246']);
        Parishes::create(['name' => 'Aricagua', 'id_municipalities' => '246']);
        Parishes::create(['name' => 'Cogollar', 'id_municipalities' => '246']);
        Parishes::create(['name' => 'San Fernando', 'id_municipalities' => '246']);
        Parishes::create(['name' => 'San Lorenzo', 'id_municipalities' => '246']);
        Parishes::create(['name' => 'Villa Frontado (Muelle de Cariaco)', 'id_municipalities' => '247']);
        Parishes::create(['name' => 'Catuaro', 'id_municipalities' => '247']);
        Parishes::create(['name' => 'Rendón', 'id_municipalities' => '247']);
        Parishes::create(['name' => 'San Cruz', 'id_municipalities' => '247']);
        Parishes::create(['name' => 'Santa María', 'id_municipalities' => '247']);
        Parishes::create(['name' => 'Altagracia', 'id_municipalities' => '248']);
        Parishes::create(['name' => 'Santa Inés', 'id_municipalities' => '248']);
        Parishes::create(['name' => 'Valentín Valiente', 'id_municipalities' => '248']);
        Parishes::create(['name' => 'Ayacucho', 'id_municipalities' => '248']);
        Parishes::create(['name' => 'San Juan', 'id_municipalities' => '248']);
        Parishes::create(['name' => 'Raúl Leoni', 'id_municipalities' => '248']);
        Parishes::create(['name' => 'Gran Mariscal', 'id_municipalities' => '248']);
        Parishes::create(['name' => 'Cristóbal Colón', 'id_municipalities' => '249']);
        Parishes::create(['name' => 'Bideau', 'id_municipalities' => '249']);
        Parishes::create(['name' => 'Punta de Piedras', 'id_municipalities' => '249']);
        Parishes::create(['name' => 'Güiria', 'id_municipalities' => '249']);
        Parishes::create(['name' => 'Andrés Bello', 'id_municipalities' => '250']);
        Parishes::create(['name' => 'Antonio Rómulo Costa', 'id_municipalities' => '251']);
        Parishes::create(['name' => 'Ayacucho', 'id_municipalities' => '252']);
        Parishes::create(['name' => 'Rivas Berti', 'id_municipalities' => '252']);
        Parishes::create(['name' => 'San Pedro del Río', 'id_municipalities' => '252']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '253']);
        Parishes::create(['name' => 'Palotal', 'id_municipalities' => '253']);
        Parishes::create(['name' => 'General Juan Vicente Gómez', 'id_municipalities' => '253']);
        Parishes::create(['name' => 'Isaías Medina Angarita', 'id_municipalities' => '253']);
        Parishes::create(['name' => 'Cárdenas', 'id_municipalities' => '254']);
        Parishes::create(['name' => 'Amenodoro Ángel Lamus', 'id_municipalities' => '254']);
        Parishes::create(['name' => 'La Florida', 'id_municipalities' => '254']);
        Parishes::create(['name' => 'Córdoba', 'id_municipalities' => '255']);
        Parishes::create(['name' => 'Fernández Feo', 'id_municipalities' => '256']);
        Parishes::create(['name' => 'Alberto Adriani', 'id_municipalities' => '256']);
        Parishes::create(['name' => 'Santo Domingo', 'id_municipalities' => '256']);
        Parishes::create(['name' => 'Francisco de Miranda', 'id_municipalities' => '257']);
        Parishes::create(['name' => 'García de Hevia', 'id_municipalities' => '258']);
        Parishes::create(['name' => 'Boca de Grita', 'id_municipalities' => '258']);
        Parishes::create(['name' => 'José Antonio Páez', 'id_municipalities' => '258']);
        Parishes::create(['name' => 'Guásimos', 'id_municipalities' => '259']);
        Parishes::create(['name' => 'Independencia', 'id_municipalities' => '260']);
        Parishes::create(['name' => 'Juan Germán Roscio', 'id_municipalities' => '260']);
        Parishes::create(['name' => 'Román Cárdenas', 'id_municipalities' => '260']);
        Parishes::create(['name' => 'Jáuregui', 'id_municipalities' => '261']);
        Parishes::create(['name' => 'Emilio Constantino Guerrero', 'id_municipalities' => '261']);
        Parishes::create(['name' => 'Monseñor Miguel Antonio Salas', 'id_municipalities' => '261']);
        Parishes::create(['name' => 'José María Vargas', 'id_municipalities' => '262']);
        Parishes::create(['name' => 'Junín', 'id_municipalities' => '263']);
        Parishes::create(['name' => 'La Petrólea', 'id_municipalities' => '263']);
        Parishes::create(['name' => 'Quinimarí', 'id_municipalities' => '263']);
        Parishes::create(['name' => 'Bramón', 'id_municipalities' => '263']);
        Parishes::create(['name' => 'Libertad', 'id_municipalities' => '264']);
        Parishes::create(['name' => 'Cipriano Castro', 'id_municipalities' => '264']);
        Parishes::create(['name' => 'Manuel Felipe Rugeles', 'id_municipalities' => '264']);
        Parishes::create(['name' => 'Libertador', 'id_municipalities' => '265']);
        Parishes::create(['name' => 'Doradas', 'id_municipalities' => '265']);
        Parishes::create(['name' => 'Emeterio Ochoa', 'id_municipalities' => '265']);
        Parishes::create(['name' => 'San Joaquín de Navay', 'id_municipalities' => '265']);
        Parishes::create(['name' => 'Lobatera', 'id_municipalities' => '266']);
        Parishes::create(['name' => 'Constitución', 'id_municipalities' => '266']);
        Parishes::create(['name' => 'Michelena', 'id_municipalities' => '267']);
        Parishes::create(['name' => 'Panamericano', 'id_municipalities' => '268']);
        Parishes::create(['name' => 'La Palmita', 'id_municipalities' => '268']);
        Parishes::create(['name' => 'Pedro María Ureña', 'id_municipalities' => '269']);
        Parishes::create(['name' => 'Nueva Arcadia', 'id_municipalities' => '269']);
        Parishes::create(['name' => 'Delicias', 'id_municipalities' => '270']);
        Parishes::create(['name' => 'Pecaya', 'id_municipalities' => '270']);
        Parishes::create(['name' => 'Samuel Darío Maldonado', 'id_municipalities' => '271']);
        Parishes::create(['name' => 'Boconó', 'id_municipalities' => '271']);
        Parishes::create(['name' => 'Hernández', 'id_municipalities' => '271']);
        Parishes::create(['name' => 'La Concordia', 'id_municipalities' => '272']);
        Parishes::create(['name' => 'San Juan Bautista', 'id_municipalities' => '272']);
        Parishes::create(['name' => 'Pedro María Morantes', 'id_municipalities' => '272']);
        Parishes::create(['name' => 'San Sebastián', 'id_municipalities' => '272']);
        Parishes::create(['name' => 'Dr. Francisco Romero Lobo', 'id_municipalities' => '272']);
        Parishes::create(['name' => 'Seboruco', 'id_municipalities' => '273']);
        Parishes::create(['name' => 'Simón Rodríguez', 'id_municipalities' => '274']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '275']);
        Parishes::create(['name' => 'Eleazar López Contreras', 'id_municipalities' => '275']);
        Parishes::create(['name' => 'San Pablo', 'id_municipalities' => '275']);
        Parishes::create(['name' => 'Torbes', 'id_municipalities' => '276']);
        Parishes::create(['name' => 'Uribante', 'id_municipalities' => '277']);
        Parishes::create(['name' => 'Cárdenas', 'id_municipalities' => '277']);
        Parishes::create(['name' => 'Juan Pablo Peñalosa', 'id_municipalities' => '277']);
        Parishes::create(['name' => 'Potosí', 'id_municipalities' => '277']);
        Parishes::create(['name' => 'San Judas Tadeo', 'id_municipalities' => '278']);
        Parishes::create(['name' => 'Araguaney', 'id_municipalities' => '279']);
        Parishes::create(['name' => 'El Jaguito', 'id_municipalities' => '279']);
        Parishes::create(['name' => 'La Esperanza', 'id_municipalities' => '279']);
        Parishes::create(['name' => 'Santa Isabel', 'id_municipalities' => '279']);
        Parishes::create(['name' => 'Boconó', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'El Carmen', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Mosquey', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Ayacucho', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Burbusay', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'General Ribas', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Guaramacal', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Vega de Guaramacal', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Monseñor Jáuregui', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Rafael Rangel', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'San Miguel', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'San José', 'id_municipalities' => '280']);
        Parishes::create(['name' => 'Sabana Grande', 'id_municipalities' => '281']);
        Parishes::create(['name' => 'Cheregüé', 'id_municipalities' => '281']);
        Parishes::create(['name' => 'Granados', 'id_municipalities' => '281']);
        Parishes::create(['name' => 'Arnoldo Gabaldón', 'id_municipalities' => '282']);
        Parishes::create(['name' => 'Bolivia', 'id_municipalities' => '282']);
        Parishes::create(['name' => 'Carrillo', 'id_municipalities' => '282']);
        Parishes::create(['name' => 'Cegarra', 'id_municipalities' => '282']);
        Parishes::create(['name' => 'Chejendé', 'id_municipalities' => '282']);
        Parishes::create(['name' => 'Manuel Salvador Ulloa', 'id_municipalities' => '282']);
        Parishes::create(['name' => 'San José', 'id_municipalities' => '282']);
        Parishes::create(['name' => 'Carache', 'id_municipalities' => '283']);
        Parishes::create(['name' => 'La Concepción', 'id_municipalities' => '283']);
        Parishes::create(['name' => 'Cuicas', 'id_municipalities' => '283']);
        Parishes::create(['name' => 'Panamericana', 'id_municipalities' => '283']);
        Parishes::create(['name' => 'Santa Cruz', 'id_municipalities' => '283']);
        Parishes::create(['name' => 'Escuque', 'id_municipalities' => '284']);
        Parishes::create(['name' => 'La Unión', 'id_municipalities' => '284']);
        Parishes::create(['name' => 'Santa Rita', 'id_municipalities' => '284']);
        Parishes::create(['name' => 'Sabana Libre', 'id_municipalities' => '284']);
        Parishes::create(['name' => 'El Socorro', 'id_municipalities' => '285']);
        Parishes::create(['name' => 'Los Caprichos', 'id_municipalities' => '285']);
        Parishes::create(['name' => 'Antonio José de Sucre', 'id_municipalities' => '285']);
        Parishes::create(['name' => 'Campo Elías', 'id_municipalities' => '286']);
        Parishes::create(['name' => 'Arnoldo Gabaldón', 'id_municipalities' => '286']);
        Parishes::create(['name' => 'Santa Apolonia', 'id_municipalities' => '287']);
        Parishes::create(['name' => 'El Progreso', 'id_municipalities' => '287']);
        Parishes::create(['name' => 'La Ceiba', 'id_municipalities' => '287']);
        Parishes::create(['name' => 'Tres de Febrero', 'id_municipalities' => '287']);
        Parishes::create(['name' => 'El Dividive', 'id_municipalities' => '288']);
        Parishes::create(['name' => 'Agua Santa', 'id_municipalities' => '288']);
        Parishes::create(['name' => 'Agua Caliente', 'id_municipalities' => '288']);
        Parishes::create(['name' => 'El Cenizo', 'id_municipalities' => '288']);
        Parishes::create(['name' => 'Valerita', 'id_municipalities' => '288']);
        Parishes::create(['name' => 'Monte Carmelo', 'id_municipalities' => '289']);
        Parishes::create(['name' => 'Buena Vista', 'id_municipalities' => '289']);
        Parishes::create(['name' => 'Santa María del Horcón', 'id_municipalities' => '289']);
        Parishes::create(['name' => 'Motatán', 'id_municipalities' => '290']);
        Parishes::create(['name' => 'El Baño', 'id_municipalities' => '290']);
        Parishes::create(['name' => 'Jalisco', 'id_municipalities' => '290']);
        Parishes::create(['name' => 'Pampán', 'id_municipalities' => '291']);
        Parishes::create(['name' => 'Flor de Patria', 'id_municipalities' => '291']);
        Parishes::create(['name' => 'La Paz', 'id_municipalities' => '291']);
        Parishes::create(['name' => 'Santa Ana', 'id_municipalities' => '291']);
        Parishes::create(['name' => 'Pampanito', 'id_municipalities' => '292']);
        Parishes::create(['name' => 'La Concepción', 'id_municipalities' => '292']);
        Parishes::create(['name' => 'Pampanito II', 'id_municipalities' => '292']);
        Parishes::create(['name' => 'Betijoque', 'id_municipalities' => '293']);
        Parishes::create(['name' => 'José Gregorio Hernández', 'id_municipalities' => '293']);
        Parishes::create(['name' => 'La Pueblita', 'id_municipalities' => '293']);
        Parishes::create(['name' => 'Los Cedros', 'id_municipalities' => '293']);
        Parishes::create(['name' => 'Carvajal', 'id_municipalities' => '294']);
        Parishes::create(['name' => 'Campo Alegre', 'id_municipalities' => '294']);
        Parishes::create(['name' => 'Antonio Nicolás Briceño', 'id_municipalities' => '294']);
        Parishes::create(['name' => 'José Leonardo Suárez', 'id_municipalities' => '294']);
        Parishes::create(['name' => 'Sabana de Mendoza', 'id_municipalities' => '295']);
        Parishes::create(['name' => 'Junín', 'id_municipalities' => '295']);
        Parishes::create(['name' => 'Valmore Rodríguez', 'id_municipalities' => '295']);
        Parishes::create(['name' => 'El Paraíso', 'id_municipalities' => '295']);
        Parishes::create(['name' => 'Andrés Linares', 'id_municipalities' => '296']);
        Parishes::create(['name' => 'Chiquinquirá', 'id_municipalities' => '296']);
        Parishes::create(['name' => 'Cristóbal Mendoza', 'id_municipalities' => '296']);
        Parishes::create(['name' => 'Cruz Carrillo', 'id_municipalities' => '296']);
        Parishes::create(['name' => 'Matriz', 'id_municipalities' => '296']);
        Parishes::create(['name' => 'Monseñor Carrillo', 'id_municipalities' => '296']);
        Parishes::create(['name' => 'Tres Esquinas', 'id_municipalities' => '296']);
        Parishes::create(['name' => 'Cabimbú', 'id_municipalities' => '297']);
        Parishes::create(['name' => 'Jajó', 'id_municipalities' => '297']);
        Parishes::create(['name' => 'La Mesa de Esnujaque', 'id_municipalities' => '297']);
        Parishes::create(['name' => 'Santiago', 'id_municipalities' => '297']);
        Parishes::create(['name' => 'Tuñame', 'id_municipalities' => '297']);
        Parishes::create(['name' => 'La Quebrada', 'id_municipalities' => '297']);
        Parishes::create(['name' => 'Juan Ignacio Montilla', 'id_municipalities' => '298']);
        Parishes::create(['name' => 'La Beatriz', 'id_municipalities' => '298']);
        Parishes::create(['name' => 'La Puerta', 'id_municipalities' => '298']);
        Parishes::create(['name' => 'Mendoza del Valle de Momboy', 'id_municipalities' => '298']);
        Parishes::create(['name' => 'Mercedes Díaz', 'id_municipalities' => '298']);
        Parishes::create(['name' => 'San Luis', 'id_municipalities' => '298']);
        Parishes::create(['name' => 'Caraballeda', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Carayaca', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Carlos Soublette', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Caruao Chuspa', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Catia La Mar', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'El Junko', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'La Guaira', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Macuto', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Maiquetía', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Naiguatá', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Urimare', 'id_municipalities' => '299']);
        Parishes::create(['name' => 'Arístides Bastidas', 'id_municipalities' => '300']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '301']);
        Parishes::create(['name' => 'Chivacoa', 'id_municipalities' => '302']);
        Parishes::create(['name' => 'Campo Elías', 'id_municipalities' => '302']);
        Parishes::create(['name' => 'Cocorote', 'id_municipalities' => '303']);
        Parishes::create(['name' => 'Independencia', 'id_municipalities' => '304']);
        Parishes::create(['name' => 'José Antonio Páez', 'id_municipalities' => '305']);
        Parishes::create(['name' => 'La Trinidad', 'id_municipalities' => '306']);
        Parishes::create(['name' => 'Manuel Monge', 'id_municipalities' => '307']);
        Parishes::create(['name' => 'Salóm', 'id_municipalities' => '308']);
        Parishes::create(['name' => 'Temerla', 'id_municipalities' => '308']);
        Parishes::create(['name' => 'Nirgua', 'id_municipalities' => '308']);
        Parishes::create(['name' => 'San Andrés', 'id_municipalities' => '309']);
        Parishes::create(['name' => 'Yaritagua', 'id_municipalities' => '309']);
        Parishes::create(['name' => 'San Javier', 'id_municipalities' => '310']);
        Parishes::create(['name' => 'Albarico', 'id_municipalities' => '310']);
        Parishes::create(['name' => 'San Felipe', 'id_municipalities' => '310']);
        Parishes::create(['name' => 'Sucre', 'id_municipalities' => '311']);
        Parishes::create(['name' => 'Urachiche', 'id_municipalities' => '312']);
        Parishes::create(['name' => 'El Guayabo', 'id_municipalities' => '313']);
        Parishes::create(['name' => 'Farriar', 'id_municipalities' => '313']);
        Parishes::create(['name' => 'Isla de Toas', 'id_municipalities' => '314']);
        Parishes::create(['name' => 'Monagas', 'id_municipalities' => '314']);
        Parishes::create(['name' => 'San Timoteo', 'id_municipalities' => '315']);
        Parishes::create(['name' => 'General Urdaneta', 'id_municipalities' => '315']);
        Parishes::create(['name' => 'Libertador', 'id_municipalities' => '315']);
        Parishes::create(['name' => 'Marcelino Briceño', 'id_municipalities' => '315']);
        Parishes::create(['name' => 'Pueblo Nuevo', 'id_municipalities' => '315']);
        Parishes::create(['name' => 'Manuel Guanipa Matos', 'id_municipalities' => '315']);
        Parishes::create(['name' => 'Ambrosio', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'Carmen Herrera', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'La Rosa', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'Germán Ríos Linares', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'San Benito', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'Rómulo Betancourt', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'Jorge Hernández', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'Punta Gorda', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'Arístides Calvani', 'id_municipalities' => '316']);
        Parishes::create(['name' => 'Encontrados', 'id_municipalities' => '317']);
        Parishes::create(['name' => 'Udón Pérez', 'id_municipalities' => '317']);
        Parishes::create(['name' => 'Moralito', 'id_municipalities' => '318']);
        Parishes::create(['name' => 'San Carlos del Zulia', 'id_municipalities' => '318']);
        Parishes::create(['name' => 'Santa Cruz del Zulia', 'id_municipalities' => '318']);
        Parishes::create(['name' => 'Santa Bárbara', 'id_municipalities' => '318']);
        Parishes::create(['name' => 'Urribarrí', 'id_municipalities' => '318']);
        Parishes::create(['name' => 'Carlos Quevedo', 'id_municipalities' => '319']);
        Parishes::create(['name' => 'Francisco Javier Pulgar', 'id_municipalities' => '319']);
        Parishes::create(['name' => 'Simón Rodríguez', 'id_municipalities' => '319']);
        Parishes::create(['name' => 'Guamo-Gavilanes', 'id_municipalities' => '319']);
        Parishes::create(['name' => 'La Concepción', 'id_municipalities' => '321']);
        Parishes::create(['name' => 'San José', 'id_municipalities' => '321']);
        Parishes::create(['name' => 'Mariano Parra León', 'id_municipalities' => '321']);
        Parishes::create(['name' => 'José Ramón Yépez', 'id_municipalities' => '321']);
        Parishes::create(['name' => 'Jesús María Semprún', 'id_municipalities' => '322']);
        Parishes::create(['name' => 'Barí', 'id_municipalities' => '322']);
        Parishes::create(['name' => 'Concepción', 'id_municipalities' => '323']);
        Parishes::create(['name' => 'Andrés Bello', 'id_municipalities' => '323']);
        Parishes::create(['name' => 'Chiquinquirá', 'id_municipalities' => '323']);
        Parishes::create(['name' => 'El Carmelo', 'id_municipalities' => '323']);
        Parishes::create(['name' => 'Potreritos', 'id_municipalities' => '323']);
        Parishes::create(['name' => 'Libertad', 'id_municipalities' => '324']);
        Parishes::create(['name' => 'Alonso de Ojeda', 'id_municipalities' => '324']);
        Parishes::create(['name' => 'Venezuela', 'id_municipalities' => '324']);
        Parishes::create(['name' => 'Eleazar López Contreras', 'id_municipalities' => '324']);
        Parishes::create(['name' => 'Campo Lara', 'id_municipalities' => '324']);
        Parishes::create(['name' => 'Bartolomé de las Casas', 'id_municipalities' => '325']);
        Parishes::create(['name' => 'Libertad', 'id_municipalities' => '325']);
        Parishes::create(['name' => 'Río Negro', 'id_municipalities' => '325']);
        Parishes::create(['name' => 'San José de Perijá', 'id_municipalities' => '325']);
        Parishes::create(['name' => 'San Rafael', 'id_municipalities' => '326']);
        Parishes::create(['name' => 'La Sierrita', 'id_municipalities' => '326']);
        Parishes::create(['name' => 'Las Parcelas', 'id_municipalities' => '326']);
        Parishes::create(['name' => 'Luis de Vicente', 'id_municipalities' => '326']);
        Parishes::create(['name' => 'Monseñor Marcos Sergio Godoy', 'id_municipalities' => '326']);
        Parishes::create(['name' => 'Ricaurte', 'id_municipalities' => '326']);
        Parishes::create(['name' => 'Tamare', 'id_municipalities' => '326']);
        Parishes::create(['name' => 'Antonio Borjas Romero', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Bolívar', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Cacique Mara', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Carracciolo Parra Pérez', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Cecilio Acosta', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Cristo de Aranza', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Coquivacoa', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Chiquinquirá', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Francisco Eugenio Bustamante', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Idelfonzo Vásquez', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Juana de Ávila', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Luis Hurtado Higuera', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Manuel Dagnino', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Olegario Villalobos', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Raúl Leoni', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Santa Lucía', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Venancio Pulgar', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'San Isidro', 'id_municipalities' => '327']);
        Parishes::create(['name' => 'Altagracia', 'id_municipalities' => '328']);
        Parishes::create(['name' => 'Faría', 'id_municipalities' => '328']);
        Parishes::create(['name' => 'Ana María Campos', 'id_municipalities' => '328']);
        Parishes::create(['name' => 'San Antonio', 'id_municipalities' => '328']);
        Parishes::create(['name' => 'San José', 'id_municipalities' => '328']);
        Parishes::create(['name' => 'Donaldo García', 'id_municipalities' => '329']);
        Parishes::create(['name' => 'El Rosario', 'id_municipalities' => '329']);
        Parishes::create(['name' => 'Sixto Zambrano', 'id_municipalities' => '329']);
        Parishes::create(['name' => 'San Francisco', 'id_municipalities' => '330']);
        Parishes::create(['name' => 'El Bajo', 'id_municipalities' => '330']);
        Parishes::create(['name' => 'Domitila Flores', 'id_municipalities' => '330']);
        Parishes::create(['name' => 'Francisco Ochoa', 'id_municipalities' => '330']);
        Parishes::create(['name' => 'Los Cortijos', 'id_municipalities' => '330']);
        Parishes::create(['name' => 'Marcial Hernández ', 'id_municipalities' => '330']);
        Parishes::create(['name' => 'Santa Rita', 'id_municipalities' => '331']);
        Parishes::create(['name' => 'El Mene', 'id_municipalities' => '331']);
        Parishes::create(['name' => 'Pedro Lucas Urribarrí', 'id_municipalities' => '331']);
        Parishes::create(['name' => 'José Cenobio Urribarrí', 'id_municipalities' => '331']);
        Parishes::create(['name' => 'Rafael Maria Baralt', 'id_municipalities' => '332']);
        Parishes::create(['name' => 'Manuel Manrique', 'id_municipalities' => '332']);
        Parishes::create(['name' => 'Rafael Urdaneta', 'id_municipalities' => '332']);
        Parishes::create(['name' => 'Bobures', 'id_municipalities' => '333']);
        Parishes::create(['name' => 'Gibraltar', 'id_municipalities' => '333']);
        Parishes::create(['name' => 'Heras', 'id_municipalities' => '333']);
        Parishes::create(['name' => 'Monseñor Arturo Álvarez', 'id_municipalities' => '333']);
        Parishes::create(['name' => 'Rómulo Gallegos', 'id_municipalities' => '333']);
        Parishes::create(['name' => 'El Batey', 'id_municipalities' => '333']);
        Parishes::create(['name' => 'Rafael Urdaneta', 'id_municipalities' => '334']);
        Parishes::create(['name' => 'La Victoria', 'id_municipalities' => '334']);
        Parishes::create(['name' => 'Raúl Cuenca', 'id_municipalities' => '334']);
        Parishes::create(['name' => 'Sinamaica', 'id_municipalities' => '320']);
        Parishes::create(['name' => 'Alta Guajira', 'id_municipalities' => '320']);
        Parishes::create(['name' => 'Elías Sánchez Rubio', 'id_municipalities' => '320']);
        Parishes::create(['name' => 'Guajira', 'id_municipalities' => '320']);
        Parishes::create(['name' => 'Altagracia', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Antímano', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Caricuao', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Catedral', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Coche', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'El Junquito', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'El Paraíso', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'El Recreo', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'El Valle', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'La Candelaria', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'La Pastora', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'La Vega', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Macarao', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'San Agustín', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'San Bernardino', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'San José', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'San Juan', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'San Pedro', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Santa Rosalía', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Santa Teresa', 'id_municipalities' => '335']);
        Parishes::create(['name' => 'Sucre (Catia)', 'id_municipalities' => '335']);
        Parishes::create(['name' => '23 de enero', 'id_municipalities' => '335']);

    }
}
